.pragma library

// Curated emoji dataset: [char, name, keywords, category].
// Categories: 0 Smileys, 1 People, 2 Nature, 3 Food, 4 Activity,
// 5 Travel, 6 Objects, 7 Symbols.

var CATEGORIES = ["Smileys", "People", "Nature", "Food", "Activity", "Travel", "Objects", "Symbols"];

var DATA = [
    // ── 0 Smileys ──
    ["😀", "grinning face", "happy smile grin", 0],
    ["😁", "beaming face", "grin teeth happy", 0],
    ["😂", "face with tears of joy", "laugh funny lol crying", 0],
    ["🤣", "rolling on the floor laughing", "rofl lmao funny", 0],
    ["😊", "smiling face with smiling eyes", "blush happy pleased", 0],
    ["😍", "smiling face with heart eyes", "love crush adore", 0],
    ["🥰", "smiling face with hearts", "love affection", 0],
    ["😘", "face blowing a kiss", "kiss love", 0],
    ["😎", "smiling face with sunglasses", "cool confident", 0],
    ["🤔", "thinking face", "hmm ponder consider", 0],
    ["😐", "neutral face", "meh blank", 0],
    ["🙄", "face with rolling eyes", "eyeroll whatever annoyed", 0],
    ["😏", "smirking face", "smug sly", 0],
    ["😌", "relieved face", "calm phew content", 0],
    ["😴", "sleeping face", "sleep tired snore", 0],
    ["🤤", "drooling face", "drool hungry", 0],
    ["😷", "face with medical mask", "mask sick ill", 0],
    ["🤒", "face with thermometer", "sick fever ill", 0],
    ["🤕", "face with head bandage", "injured hurt", 0],
    ["🤯", "exploding head", "mind blown shocked", 0],
    ["🥳", "partying face", "celebration birthday party", 0],
    ["😢", "crying face", "tear sad upset", 0],
    ["😭", "loudly crying face", "sob bawling wail", 0],
    ["😡", "enraged face", "angry mad rage red", 0],
    ["🤬", "face with symbols on mouth", "swearing cursing", 0],
    ["🥺", "pleading face", "puppy eyes beg", 0],
    ["😬", "grimacing face", "awkward yikes", 0],
    ["🤥", "lying face", "liar pinocchio", 0],
    ["🤫", "shushing face", "quiet secret silence", 0],
    ["🤭", "face with hand over mouth", "giggle oops", 0],
    ["🫡", "saluting face", "salute respect", 0],
    ["🫠", "melting face", "melt hot embarrassed", 0],
    ["🫣", "face with peeking eye", "peek hide shy", 0],
    ["💀", "skull", "dead skeleton lol", 0],
    ["👻", "ghost", "spooky boo halloween", 0],
    ["🤖", "robot", "bot android", 0],
    ["💩", "pile of poo", "poop shit funny", 0],
    ["😺", "grinning cat", "cat happy", 0],
    ["😸", "grinning cat with smiling eyes", "cat smile", 0],
    ["😹", "cat with tears of joy", "cat laugh funny", 0],
    ["😻", "smiling cat with heart eyes", "cat love", 0],
    ["🙈", "see no evil monkey", "monkey blind ignore", 0],
    ["🙉", "hear no evil monkey", "monkey deaf", 0],
    ["🙊", "speak no evil monkey", "monkey mute quiet", 0],
    ["💋", "kiss mark", "kiss lips lipstick", 0],
    ["❤️", "red heart", "love heart", 0],
    ["🧡", "orange heart", "love", 0],
    ["💛", "yellow heart", "love", 0],
    ["💚", "green heart", "love jealous", 0],
    ["💙", "blue heart", "love", 0],
    ["💜", "purple heart", "love", 0],
    ["🖤", "black heart", "dark love", 0],
    ["🤍", "white heart", "love pure", 0],
    ["💔", "broken heart", "heartbreak sad breakup", 0],
    ["💯", "hundred points", "perfect score 100", 0],
    ["✨", "sparkles", "shine shiny new glitter", 0],
    ["🔥", "fire", "lit hot flame", 0],
    // ── 1 People ──
    ["👋", "waving hand", "hello hi bye wave", 1],
    ["👍", "thumbs up", "yes like approve good", 1],
    ["👎", "thumbs down", "no dislike bad", 1],
    ["👏", "clapping hands", "applause bravo congrats", 1],
    ["🙌", "raising hands", "hooray celebration praise", 1],
    ["🤝", "handshake", "deal agreement shake", 1],
    ["💪", "flexed biceps", "muscle strong power", 1],
    ["🙏", "folded hands", "pray please thanks namaste", 1],
    ["👌", "ok hand", "perfect okay", 1],
    ["✌️", "victory hand", "peace two v", 1],
    ["🤞", "crossed fingers", "luck hope wish", 1],
    ["✋", "raised hand", "high five stop", 1],
    ["👊", "oncoming fist", "fist bump punch", 1],
    ["✊", "raised fist", "power solidarity", 1],
    ["🫶", "heart hands", "love care", 1],
    ["👉", "backhand index pointing right", "point right look", 1],
    ["👈", "backhand index pointing left", "point left look", 1],
    ["👆", "backhand index pointing up", "point up", 1],
    ["👇", "backhand index pointing down", "point down", 1],
    ["☝️", "index pointing up", "one point", 1],
    ["👀", "eyes", "looking watch see", 1],
    ["👁️", "eye", "see look vision", 1],
    ["🧠", "brain", "smart intelligent mind", 1],
    ["👄", "mouth", "lips kiss", 1],
    ["👅", "tongue", "taste", 1],
    ["👃", "nose", "smell sniff", 1],
    ["👂", "ear", "hear listen", 1],
    ["🦷", "tooth", "teeth dentist", 1],
    ["👶", "baby", "infant newborn child", 1],
    ["🧒", "child", "kid young", 1],
    ["👦", "boy", "male kid", 1],
    ["👧", "girl", "female kid", 1],
    ["🧑", "person", "adult human", 1],
    ["👨", "man", "male guy", 1],
    ["👩", "woman", "female lady", 1],
    ["🧓", "older person", "elderly old grandparent", 1],
    ["👴", "old man", "grandpa elderly", 1],
    ["👵", "old woman", "grandma elderly", 1],
    ["👮", "police officer", "cop law", 1],
    ["💂", "guard", "soldier british", 1],
    ["👷", "construction worker", "builder work", 1],
    ["🤴", "prince", "king royal crown", 1],
    ["👸", "princess", "queen royal crown", 1],
    ["👳", "person wearing turban", "turban sikh", 1],
    ["🧔", "bearded person", "beard man", 1],
    ["🤰", "pregnant woman", "pregnancy expecting", 1],
    ["🤱", "breast feeding", "nursing baby mother", 1],
    ["💃", "woman dancing", "dance salsa", 1],
    ["🕺", "man dancing", "dance disco", 1],
    ["🏃", "person running", "run sprint jog", 1],
    ["🚶", "person walking", "walk stroll", 1],
    // ── 2 Nature ──
    ["🐶", "dog face", "puppy pet", 2],
    ["🐱", "cat face", "kitten pet", 2],
    ["🦊", "fox", "clever orange", 2],
    ["🐻", "bear", "teddy", 2],
    ["🐼", "panda", "bamboo china", 2],
    ["🐨", "koala", "australia", 2],
    ["🐸", "frog", "toad", 2],
    ["🦁", "lion", "king jungle", 2],
    ["🐯", "tiger", "stripes", 2],
    ["🦄", "unicorn", "magic fantasy rainbow", 2],
    ["🐝", "honeybee", "bee buzz honey", 2],
    ["🦋", "butterfly", "caterpillar pretty", 2],
    ["🐢", "turtle", "tortoise slow", 2],
    ["🐙", "octopus", "squid tentacles", 2],
    ["🦀", "crab", "seafood", 2],
    ["🐬", "dolphin", "smart sea", 2],
    ["🐳", "spouting whale", "whale ocean", 2],
    ["🦈", "shark", "jaws danger", 2],
    ["🌸", "cherry blossom", "flower spring sakura", 2],
    ["🌹", "rose", "flower love red", 2],
    ["🌻", "sunflower", "flower sun summer", 2],
    ["🌷", "tulip", "flower spring", 2],
    ["🌲", "evergreen tree", "pine forest christmas", 2],
    ["🌳", "deciduous tree", "green forest", 2],
    ["🌵", "cactus", "desert succulent", 2],
    ["🍀", "four leaf clover", "lucky ireland", 2],
    ["🍁", "maple leaf", "canada autumn fall", 2],
    ["🌙", "crescent moon", "night sleep", 2],
    ["☀️", "sun", "sunny day bright", 2],
    ["⭐", "star", "favorite night", 2],
    ["🌈", "rainbow", "pride colorful", 2],
    ["⚡", "high voltage", "lightning zap fast", 2],
    ["❄️", "snowflake", "snow winter cold", 2],
    ["⛄", "snowman", "winter snow", 2],
    ["🌊", "water wave", "ocean surf sea", 2],
    ["🌍", "globe showing europe africa", "earth world planet", 2],
    ["🌎", "globe showing americas", "earth world", 2],
    ["🌏", "globe showing asia australia", "earth world", 2],
    ["🌕", "full moon", "night", 2],
    ["☁️", "cloud", "weather overcast", 2],
    ["🌧️", "cloud with rain", "rainy weather", 2],
    ["⛈️", "cloud with lightning and rain", "storm thunder", 2],
    // ── 3 Food ──
    ["🍎", "red apple", "fruit healthy", 3],
    ["🍏", "green apple", "fruit", 3],
    ["🍇", "grapes", "fruit wine", 3],
    ["🍓", "strawberry", "berry fruit", 3],
    ["🍒", "cherries", "berry fruit", 3],
    ["🍑", "peach", "fruit butt", 3],
    ["🍍", "pineapple", "tropical fruit", 3],
    ["🥑", "avocado", "guacamole healthy", 3],
    ["🍕", "pizza", "slice cheese italian", 3],
    ["🍔", "hamburger", "burger fast food", 3],
    ["🍟", "french fries", "fries fast food", 3],
    ["🌮", "taco", "mexican", 3],
    ["🍩", "doughnut", "donut sweet dessert", 3],
    ["🍪", "cookie", "biscuit sweet", 3],
    ["🎂", "birthday cake", "birthday party dessert", 3],
    ["🍰", "shortcake", "cake dessert slice", 3],
    ["🍫", "chocolate bar", "candy sweet", 3],
    ["🍿", "popcorn", "movie snack cinema", 3],
    ["☕", "hot beverage", "coffee tea morning", 3],
    ["🍵", "teacup without handle", "tea green matcha", 3],
    ["🧋", "bubble tea", "boba milk tea", 3],
    ["🍺", "beer mug", "beer drink cheers", 3],
    ["🍷", "wine glass", "wine red alcohol", 3],
    ["🥂", "clinking glasses", "cheers toast champagne", 3],
    ["🍸", "cocktail glass", "martini drink", 3],
    ["🥤", "cup with straw", "soda drink", 3],
    ["🧃", "beverage box", "juice", 3],
    ["🍦", "soft ice cream", "icecream dessert summer", 3],
    ["🍉", "watermelon", "fruit summer", 3],
    ["🥐", "croissant", "french breakfast pastry", 3],
    ["🥨", "pretzel", "german snack", 3],
    ["🧀", "cheese wedge", "cheese", 3],
    ["🍳", "cooking", "fried egg breakfast", 3],
    ["🥗", "green salad", "healthy vegetables", 3],
    ["🍜", "steaming bowl", "ramen noodles soup", 3],
    ["🍣", "sushi", "japanese fish", 3],
    // ── 4 Activity ──
    ["⚽", "soccer ball", "football sport", 4],
    ["🏀", "basketball", "sport hoops", 4],
    ["🏈", "american football", "nfl sport", 4],
    ["⚾", "baseball", "sport ball", 4],
    ["🎾", "tennis", "sport racket", 4],
    ["🏆", "trophy", "winner champion award", 4],
    ["🥇", "1st place medal", "gold winner first", 4],
    ["🎮", "video game", "gaming controller gamepad", 4],
    ["🕹️", "joystick", "arcade game retro", 4],
    ["🎲", "game die", "dice random board", 4],
    ["🃏", "joker", "poker card wild", 4],
    ["🎯", "direct hit", "target bullseye darts", 4],
    ["🎸", "guitar", "rock music instrument", 4],
    ["🎹", "musical keyboard", "piano music", 4],
    ["🎺", "trumpet", "brass music jazz", 4],
    ["🥁", "drum", "music beat", 4],
    ["🎤", "microphone", "karaoke sing", 4],
    ["🎧", "headphone", "music earbuds listen", 4],
    ["🎨", "artist palette", "art paint design", 4],
    ["🎭", "performing arts", "theater drama masks", 4],
    ["🎪", "circus tent", "carnival show", 4],
    ["🎬", "clapper board", "movie film cinema", 4],
    ["🏋️", "person lifting weights", "gym workout fitness", 4],
    ["🚴", "person biking", "cycling bicycle", 4],
    ["🏊", "person swimming", "swim pool", 4],
    ["⛷️", "skier", "skiing snow winter", 4],
    ["🏄", "person surfing", "surf wave", 4],
    ["🧘", "person in lotus position", "yoga meditate zen", 4],
    ["🎳", "bowling", "strike spare", 4],
    ["🏓", "ping pong", "table tennis", 4],
    // ── 5 Travel ──
    ["🚗", "automobile", "car drive", 5],
    ["🚕", "taxi", "cab uber", 5],
    ["🚌", "bus", "transit", 5],
    ["🚲", "bicycle", "bike cycling", 5],
    ["✈️", "airplane", "flight travel plane", 5],
    ["🚀", "rocket", "space launch ship", 5],
    ["🚂", "locomotive", "train steam", 5],
    ["⛵", "sailboat", "sailing boat sea", 5],
    ["🗺️", "world map", "map travel navigation", 5],
    ["🧭", "compass", "navigation direction north", 5],
    ["🏠", "house", "home", 5],
    ["🏢", "office building", "work building", 5],
    ["🏥", "hospital", "doctor health", 5],
    ["🏫", "school", "education building", 5],
    ["⛺", "tent", "camping outdoors", 5],
    ["🏖️", "beach with umbrella", "vacation summer sea", 5],
    ["🗽", "statue of liberty", "new york usa", 5],
    ["🗼", "tokyo tower", "japan tokyo", 5],
    ["⛩️", "shinto shrine", "japan temple torii", 5],
    ["🎡", "ferris wheel", "carnival fair amusement", 5],
    ["🎢", "roller coaster", "amusement thrill", 5],
    ["🏰", "castle", "fort medieval european", 5],
    ["⛪", "church", "christian chapel wedding", 5],
    ["🕌", "mosque", "islam muslim", 5],
    ["🛕", "hindu temple", "india temple", 5],
    ["🕍", "synagogue", "jewish judaism", 5],
    ["⛽", "fuel pump", "gas petrol station", 5],
    ["🚦", "traffic light", "stoplight signal", 5],
    ["🛫", "airplane departure", "takeoff flight", 5],
    ["🛬", "airplane arrival", "landing flight", 5],
    // ── 6 Objects ──
    ["💡", "light bulb", "idea bright think", 6],
    ["📱", "mobile phone", "iphone smartphone", 6],
    ["💻", "laptop", "computer macbook", 6],
    ["🖥️", "desktop computer", "pc monitor", 6],
    ["⌨️", "keyboard", "typing keys", 6],
    ["🖱️", "computer mouse", "click", 6],
    ["📷", "camera", "photo picture", 6],
    ["📹", "video camera", "film record", 6],
    ["🔑", "key", "lock password secret", 6],
    ["🔒", "locked", "lock secure private", 6],
    ["🔓", "unlocked", "open lock", 6],
    ["🎁", "wrapped gift", "present birthday surprise", 6],
    ["📚", "books", "library read study", 6],
    ["📖", "open book", "read novel", 6],
    ["✏️", "pencil", "write draw edit", 6],
    ["🖊️", "pen", "write sign ballpoint", 6],
    ["📎", "paperclip", "attach clip", 6],
    ["✂️", "scissors", "cut snip", 6],
    ["🔋", "battery", "power charge energy", 6],
    ["🔌", "electric plug", "power outlet", 6],
    ["💾", "floppy disk", "save retro", 6],
    ["💿", "optical disk", "cd dvd", 6],
    ["📀", "dvd", "disk movie", 6],
    ["🔍", "magnifying glass tilted left", "search find zoom", 6],
    ["🔎", "magnifying glass tilted right", "search find", 6],
    ["🔧", "wrench", "tool fix settings", 6],
    ["🔨", "hammer", "tool build", 6],
    ["🧲", "magnet", "attract horseshoe", 6],
    ["🧪", "test tube", "science lab experiment", 6],
    ["🔬", "microscope", "science zoom lab", 6],
    ["💉", "syringe", "vaccine shot needle", 6],
    ["💊", "pill", "medicine drugs", 6],
    ["🩹", "adhesive bandage", "bandaid hurt", 6],
    ["🚽", "toilet", "bathroom wc", 6],
    ["🛁", "bathtub", "bath shower", 6],
    ["🪑", "chair", "seat sit", 6],
    ["🛋️", "couch and lamp", "sofa furniture", 6],
    ["🚪", "door", "enter exit", 6],
    ["🪞", "mirror", "reflect", 6],
    ["🪟", "window", "glass view", 6],
    ["🧹", "broom", "clean sweep", 6],
    ["🧺", "basket", "laundry picnic", 6],
    ["🧸", "teddy bear", "plush toy cute", 6],
    ["🪆", "nesting dolls", "matryoshka russian", 6],
    ["⏰", "alarm clock", "wake time morning", 6],
    ["⌚", "watch", "time wrist apple", 6],
    // ── 7 Symbols ──
    ["✅", "check mark button", "done yes ok correct", 7],
    ["❌", "cross mark", "no wrong x delete", 7],
    ["⚠️", "warning", "alert caution danger", 7],
    ["♻️", "recycling symbol", "recycle green reuse", 7],
    ["💬", "speech balloon", "chat talk comment message", 7],
    ["💭", "thought balloon", "think dream imagine", 7],
    ["🗯️", "right anger bubble", "angry rant", 7],
    ["❓", "question mark", "question confused help", 7],
    ["❗", "exclamation mark", "alert important bang", 7],
    ["‼️", "double exclamation mark", "emphasis", 7],
    ["⁉️", "exclamation question mark", "surprise huh", 7],
    ["💢", "anger symbol", "mad furious rage", 7],
    ["💤", "zzz", "sleep snore tired", 7],
    ["⛔", "no entry", "prohibited forbidden stop", 7],
    ["🚫", "prohibited", "banned no blocked", 7],
    ["⬆️", "up arrow", "north top", 7],
    ["⬇️", "down arrow", "south bottom", 7],
    ["⬅️", "left arrow", "west back previous", 7],
    ["➡️", "right arrow", "east next forward", 7],
    ["↩️", "right arrow curving left", "return back undo", 7],
    ["↪️", "left arrow curving right", "forward redo", 7],
    ["🔃", "clockwise vertical arrows", "reload refresh sync", 7],
    ["🔀", "shuffle tracks button", "random shuffle", 7],
    ["🔁", "repeat button", "loop again", 7],
    ["▶️", "play button", "play start", 7],
    ["⏸️", "pause button", "pause hold wait", 7],
    ["⏹️", "stop button", "stop end", 7],
    ["⏺️", "record button", "rec circle", 7],
    ["⏩", "fast forward button", "skip next", 7],
    ["⏪", "fast reverse button", "rewind back", 7],
    ["➕", "plus", "add more", 7],
    ["➖", "minus", "subtract less remove", 7],
    ["✖️", "multiply", "times x close", 7],
    ["➗", "divide", "division", 7],
    ["🟰", "heavy equals sign", "equal math", 7],
    ["™️", "trade mark", "trademark brand", 7],
    ["©️", "copyright", "c rights", 7],
    ["®️", "registered", "r trademark", 7],
    ["0️⃣", "keycap digit zero", "0 number", 7],
    ["1️⃣", "keycap digit one", "1 number", 7],
    ["2️⃣", "keycap digit two", "2 number", 7],
    ["3️⃣", "keycap digit three", "3 number", 7],
    ["4️⃣", "keycap digit four", "4 number", 7],
    ["5️⃣", "keycap digit five", "5 number", 7],
    ["6️⃣", "keycap digit six", "6 number", 7],
    ["7️⃣", "keycap digit seven", "7 number", 7],
    ["8️⃣", "keycap digit eight", "8 number", 7],
    ["9️⃣", "keycap digit nine", "9 number", 7],
    ["#️⃣", "keycap number sign", "hash pound hashtag", 7],
    ["*️⃣", "keycap asterisk", "star key", 7],
    ["🆎", "AB button", "blood type ab", 7],
    ["🆘", "SOS button", "help emergency", 7],
    ["🆙", "UP button", "up vote", 7],
    ["🆒", "COOL button", "cool", 7],
    ["🆕", "NEW button", "new fresh", 7],
    ["🆓", "FREE button", "free", 7],
    ["💲", "heavy dollar sign", "money dollar price", 7],
    ["💱", "currency exchange", "money forex convert", 7],
];

var _index = null;

function _buildIndex() {
    if (_index)
        return _index;
    _index = {};
    for (var i = 0; i < DATA.length; i++) {
        var e = DATA[i];
        _index[e[0]] = {
            "char": e[0],
            "name": e[1],
            "keywords": e[2],
            "category": e[3]
        };
    }
    return _index;
}

// Resolve a char to its entry; unknown chars get a generic entry.
function lookup(ch) {
    var idx = _buildIndex();
    if (idx[ch])
        return idx[ch];
    return {
        "char": ch,
        "name": "emoji",
        "keywords": "",
        "category": -1
    };
}

// All entries of a category as objects.
function byCategory(cat) {
    var out = [];
    for (var i = 0; i < DATA.length; i++) {
        if (DATA[i][3] === cat)
            out.push(lookup(DATA[i][0]));
    }
    return out;
}

// Substring search across name + keywords. All tokens must match.
function search(query) {
    var q = (query || "").toLowerCase().trim();
    if (!q)
        return [];
    var tokens = q.split(/\s+/);
    var out = [];
    for (var i = 0; i < DATA.length && out.length < 200; i++) {
        var e = DATA[i];
        var hay = (e[1] + " " + e[2]).toLowerCase();
        var ok = true;
        for (var t = 0; t < tokens.length; t++) {
            if (hay.indexOf(tokens[t]) === -1) {
                ok = false;
                break;
            }
        }
        if (ok)
            out.push(lookup(e[0]));
    }
    return out;
}

function categoryName(cat) {
    return CATEGORIES[cat] || "";
}
